version: '3.8'

services:
  # Spring Boot Application - connects to your existing Oracle database
  spring-boot-app:
    build: .
    container_name: hello-world-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Connect to your existing Oracle database on localhost
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@host.docker.internal:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=hr
      - SPRING_DATASOURCE_PASSWORD=hr
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    # Use host networking to access your local Oracle database
    network_mode: "host"
