-- =====================================================
-- Flyway Migration: V4__Insert_Sample_Employees.sql
-- Description: Insert sample employee data for testing
-- Author: Mahendra Chaurasia
-- Date: 2025-10-15
-- =====================================================

-- Insert sample employees for testing and demonstration
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (1, 'John', 'Doe', 'john.doe@company.com', '555-0101', DATE '2020-01-15', 'IT_PROG', 75000.00, NULL, NULL, 10);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (2, 'Jane', 'Smith', 'jane.smith@company.com', '555-0102', DATE '2019-03-20', 'IT_PROG', 80000.00, NULL, 1, 10);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (3, 'Bob', 'Johnson', 'bob.johnson@company.com', '555-0103', DATE '2021-06-10', 'SALES_REP', 65000.00, 0.05, 2, 20);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (4, 'Alice', 'Brown', 'alice.brown@company.com', '555-0104', DATE '2018-09-05', 'MANAGER', 95000.00, NULL, NULL, 10);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (5, 'Charlie', 'Wilson', 'charlie.wilson@company.com', '555-0105', DATE '2022-02-14', 'SALES_REP', 70000.00, 0.03, 4, 20);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (6, 'Diana', 'Davis', 'diana.davis@company.com', '555-0106', DATE '2020-11-30', 'HR_REP', 60000.00, NULL, 4, 30);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (7, 'Eve', 'Miller', 'eve.miller@company.com', '555-0107', DATE '2021-08-22', 'IT_PROG', 78000.00, NULL, 1, 10);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (8, 'Frank', 'Garcia', 'frank.garcia@company.com', '555-0108', DATE '2019-12-03', 'SALES_MGR', 85000.00, NULL, NULL, 20);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (9, 'Grace', 'Martinez', 'grace.martinez@company.com', '555-0109', DATE '2022-05-18', 'IT_PROG', 72000.00, NULL, 1, 10);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES (10, 'Henry', 'Anderson', 'henry.anderson@company.com', '555-0110', DATE '2020-07-25', 'SALES_REP', 68000.00, 0.04, 8, 20);
