name: Performance Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 8 * * 0' # Weekly on Sunday at 8 AM

jobs:
  performance-test:
    runs-on: ubuntu-latest
    
    # Oracle database service removed due to startup issues in GitHub Actions
    # Performance tests will run without database dependency

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build application
      run: mvn clean package -DskipTests
      env:
        SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
        SPRING_DATASOURCE_USERNAME: sa
        SPRING_DATASOURCE_PASSWORD: 
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver

    - name: Start application (without database)
      run: |
        nohup java -jar target/spring-boot-employee-management-1.0.0.jar \
          --spring.datasource.url=jdbc:h2:mem:testdb \
          --spring.datasource.username=sa \
          --spring.datasource.password= \
          --spring.datasource.driver-class-name=org.h2.Driver \
          --server.port=8080 > app.log 2>&1 &
        sleep 30

    - name: Run performance tests
      run: |
        # Install Apache Bench
        sudo apt-get update
        sudo apt-get install -y apache2-utils
        
        # Wait for application to start
        timeout 60 bash -c 'until curl -f http://localhost:8080/actuator/health; do sleep 2; done'
        
        # Run performance tests
        echo "Running performance tests..."
        
        # Test health endpoint
        ab -n 100 -c 10 http://localhost:8080/actuator/health > health-test.txt
        
        # Test API endpoints (with authentication)
        echo "Testing API endpoints..."
        ab -n 50 -c 5 -H "Authorization: Basic YWRtaW46YWRtaW4=" http://localhost:8080/api/employees > api-test.txt

    - name: Generate performance report
      run: |
        echo "# Performance Test Report" > performance-report.md
        echo "Generated on: $(date)" >> performance-report.md
        echo "" >> performance-report.md
        echo "## Health Endpoint Performance" >> performance-report.md
        cat health-test.txt >> performance-report.md
        echo "" >> performance-report.md
        echo "## API Endpoint Performance" >> performance-report.md
        cat api-test.txt >> performance-report.md

    - name: Upload performance results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-test-results
        path: |
          performance-report.md
          health-test.txt
          api-test.txt
          app.log

    - name: Cleanup
      if: always()
      run: |
        pkill -f spring-boot-employee-management || true
