name: Quality Metrics

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 6 AM

jobs:
  quality-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run SonarQube analysis
      run: |
        echo "SonarQube analysis would run here if configured"
        echo "To enable SonarQube, add SONAR_TOKEN to repository secrets"

    - name: Run SpotBugs analysis
      run: mvn spotbugs:spotbugs
      continue-on-error: true

    - name: Run Checkstyle analysis
      run: mvn checkstyle:checkstyle
      continue-on-error: true

    - name: Generate quality report
      run: |
        echo "# Quality Metrics Report" > quality-report.md
        echo "Generated on: $(date)" >> quality-report.md
        echo "" >> quality-report.md
        echo "## Code Quality Metrics" >> quality-report.md
        echo "- Lines of Code: $(find src -name '*.java' | xargs wc -l | tail -1)" >> quality-report.md
        echo "- Number of Classes: $(find src -name '*.java' | wc -l)" >> quality-report.md
        echo "- Test Coverage: Available in CI/CD pipeline" >> quality-report.md

    - name: Upload quality artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: quality-metrics
        path: |
          target/spotbugsXml.xml
          target/checkstyle-result.xml
          quality-report.md

  technical-debt:
    runs-on: ubuntu-latest
    needs: quality-analysis
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Analyze technical debt
      run: |
        echo "# Technical Debt Analysis" > technical-debt.md
        echo "Generated on: $(date)" >> technical-debt.md
        echo "" >> technical-debt.md
        echo "## Code Complexity" >> technical-debt.md
        echo "- Cyclomatic Complexity: To be analyzed by SonarQube" >> technical-debt.md
        echo "- Code Duplication: To be analyzed by SonarQube" >> technical-debt.md
        echo "- Maintainability Index: To be analyzed by SonarQube" >> technical-debt.md

    - name: Upload technical debt report
      uses: actions/upload-artifact@v3
      with:
        name: technical-debt-analysis
        path: technical-debt.md
